version: '3.8'

services:
  trino-lcm:
    build:
      context: ..
      dockerfile: Docker-env/Dockerfile
    volumes:
      - ..:/app
      - ../explain_analyze_results:/app/explain_analyze_results
    working_dir: /app
    runtime: nvidia
    environment:
      - PYTHONPATH=/app/src
      - DGLBACKEND=pytorch
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NODE02={}
      - NODE03={}
      - NODE04={}
      - NODE05={}
    tty: true
    stdin_open: true
    command: bash
